### ISSUE TITLE
Reopening laptop crashes the game

### ISSUE THREAD

**Issue by Orangeboi69** [omnixerio/devices-mod#117]
**To Reproduce**
1. Place down a Laptop
2. Open it
3. Close the Interface
4. Right click on the laptop again.
(With/without ethernet cable)
- If rejoins the same world and click on the same laptop -> Crash

**Logs**
`---- Minecraft Crash Report ----
// Daisy, daisy...
Time: 2024-11-02 18:56:58
Description: Unexpected error
java.lang.NoSuchMethodError: 'java.lang.Enum org.apache.commons.lang3.EnumUtils.getEnum(java.lang.Class, java.lang.String, java.lang.Enum)'
at knot//com.ultreon.devices.core.network.TrayItemWifi.deserialize(TrayItemWifi.java:184)
at knot//com.ultreon.devices.core.TaskBar.addTrayItem(TaskBar.java:74)
at knot//com.ultreon.devices.core.TaskBar.<init>(TaskBar.java:63)
at knot//com.ultreon.devices.core.Laptop.<init>(Laptop.java:171)
at knot//com.ultreon.devices.core.Laptop.<init>(Laptop.java:127)
at knot//com.ultreon.devices.block.ClientLaptopWrapper.execute(ClientLaptopWrapper.java:10)
at knot//com.ultreon.devices.block.ComputerBlock.lambda$use$0(ComputerBlock.java:90)
at knot//dev.architectury.utils.EnvExecutor.runInEnv(EnvExecutor.java:35)
at knot//com.ultreon.devices.block.ComputerBlock.method_9534(ComputerBlock.java:89)
at knot//net.minecraft.class_4970$class_4971.method_26174(class_4970.java:1133)
at knot//net.minecraft.class_636.method_41934(class_636.java:347)
at knot//net.minecraft.class_636.method_41933(class_636.java:324)
at knot//net.minecraft.class_636.method_41931(class_636.java:278)
at knot//net.minecraft.class_636.method_2896(class_636.java:323)
at knot//net.minecraft.class_310.mixinextras$bridge$method_2896$560(class_310.java)
at knot//net.minecraft.class_310.wrapOperation$pcc000$valkyrienskies$useOriginalCrosshairForBlockPlacement(class_310.java:64064)
at knot//net.minecraft.class_310.method_1583(class_310.java:1802)
at knot//net.minecraft.class_310.redirect$cah000$betterthirdperson$onDoItemUse(class_310.java:10575)
at knot//net.minecraft.class_310.method_1508(class_310.java:2052)
at knot//net.minecraft.class_310.method_1574(class_310.java:1883)
at knot//net.minecraft.class_310.method_1523(class_310.java:1181)
at knot//net.minecraft.class_310.method_1514(class_310.java:802)
at knot//net.minecraft.client.main.Main.main(Main.java:250)
at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)`
or full server log: https://mclo.gs/5BC6OFV
**Crash report**
https://mclo.gs/tE9UiFs

**Please complete the following information:**
 - OS: Windows 11 24H2
 - Minecraft version 1.20.1
 - Devices Mod Version: 0.8.3
 - Architectury API Version: 9.2.14

**FOR FABRIC:**
 - Fabric API 0.92.2
 - Fabric loader 0.16.7

**Additional context**
Reopening the laptop just crash the game, even after reopening the world, it also crashes, even without reopening
**Additional mods used**
[Modpack Link(Pastebin)] (https://pastebin.com/kQ3j4mqi)

**Comment by QboiDev** [comment]
Huh, that's quite weird... Looks like Modrinth App downloaded a different Apache Commons version...
(Assuming you used Modrinth App, as it does show in the log)

**Comment by QboiDev** [comment]
Or maybe it's different on prod. than dev. environment. I'll check on Win11 soon.

**Comment by CrazyBobcatStudios** [comment]
Got same error. Super sad because I was excited to add this to my modpack
