### ISSUE TITLE
No initializing on dedicated server 1.18.2

### ISSUE THREAD

**Issue by 5stigma** [omnixerio/devices-mod#64]
**To Reproduce**
1. Go to run game
2. No load

**Logs**
*No log given*

**Crash report**
```
-- Head --
Thread: main
Stacktrace:
        at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:138) ~[securejarhandler-1.0.3.jar:?] {}
-- MOD devices --
Details:
        Caused by 0: java.lang.NoClassDefFoundError: net/minecraft/client/gui/GuiComponent
                at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?] {}
                at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?] {}
                at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:116) ~[securejarhandler-1.0.3.jar:?] {}
                at cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:216) ~[securejarhandler-1.0.3.jar:?] {}
                at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:226) ~[securejarhandler-1.0.3.jar:?] {}
                at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:216) ~[securejarhandler-1.0.3.jar:?] {}
                at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:132) ~[securejarhandler-1.0.3.jar:?] {}
                at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
                at com.ultreon.devices.Devices.registerApplications(Devices.java:265) ~[devices-merged-0.5.0.1.jar%2340%2351!/:?] {re:classloading}
                at com.ultreon.devices.Devices.init(Devices.java:114) ~[devices-merged-0.5.0.1.jar%2340%2351!/:?] {re:classloading}
                at com.ultreon.devices.forge.DevicesForge.commonSetup(DevicesForge.java:75) ~[devices-merged-0.5.0.1.jar%2340%2351!/:?] {re:classloading}
                at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-5.0.3.jar%232!/:?] {}
                at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-5.0.3.jar%232!/:?] {}
                at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
                at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
                at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:106) ~[javafmllanguage-1.18.2-40.2.0.jar%2344!/:?] {}
                at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:107) ~[fmlcore-1.18.2-40.2.0.jar%2343!/:?] {}
                at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
                at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
                at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
                at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
                at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
                at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
                at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

        Mod File: /C:/Users/Sstigma-pepinillo/Desktop/server 1.18 prueba/mods/devices-merged-0.5.0.1.jar#40!/META-INF/jars/forge-devices-0.5.0.1.jar
        Failure message: Devices Mod (devices) encountered an error during the common_setup event phase
                java.lang.NoClassDefFoundError: net/minecraft/client/gui/GuiComponent
        Mod Version: 0.5.0.1
        Mod Issue URL: https://github.com/Ultreon/devices-mod/issues
        Exception message: java.lang.ClassNotFoundException: net.minecraft.client.gui.GuiComponent
Stacktrace:
        at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:138) ~[securejarhandler-1.0.3.jar:?] {}
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?] {}
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?] {}
        at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:116) ~[securejarhandler-1.0.3.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:216) ~[securejarhandler-1.0.3.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:226) ~[securejarhandler-1.0.3.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:216) ~[securejarhandler-1.0.3.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:132) ~[securejarhandler-1.0.3.jar:?] {}
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
        at com.ultreon.devices.Devices.registerApplications(Devices.java:265) ~[devices-merged-0.5.0.1.jar%2340%2351!/:?] {re:classloading}
        at com.ultreon.devices.Devices.init(Devices.java:114) ~[devices-merged-0.5.0.1.jar%2340%2351!/:?] {re:classloading}
        at com.ultreon.devices.forge.DevicesForge.commonSetup(DevicesForge.java:75) ~[devices-merged-0.5.0.1.jar%2340%2351!/:?] {re:classloading}
        at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-5.0.3.jar%232!/:?] {}
        at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-5.0.3.jar%232!/:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
        at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:106) ~[javafmllanguage-1.18.2-40.2.0.jar%2344!/:?] {}
        at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:107) ~[fmlcore-1.18.2-40.2.0.jar%2343!/:?] {}
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
        at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}


-- System Details --
Details:
        Minecraft Version: 1.18.2
        Minecraft Version ID: 1.18.2
        Operating System: Windows 10 (amd64) version 10.0
        Java Version: 17.0.5, Oracle Corporation
        Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
        Memory: 1334618528 bytes (1272 MiB) / 3070230528 bytes (2928 MiB) up to 8589934592 bytes (8192 MiB)
        CPUs: 16
        Processor Vendor: GenuineIntel
        Processor Name: Intel(R) Xeon(R) CPU E5-2689 0 @ 2.60GHz
        Identifier: Intel64 Family 6 Model 45 Stepping 7
        Microarchitecture: Sandy Bridge (Server)
        Frequency (GHz): 2.59
        Number of physical packages: 1
        Number of physical CPUs: 8
        Number of logical CPUs: 16
        Graphics card #0 name: Radeon RX 570 Series
        Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
        Graphics card #0 VRAM (MB): 4095.00
        Graphics card #0 deviceId: 0x67df
        Graphics card #0 versionInfo: DriverVersion=31.0.12027.7000
        Memory slot #0 capacity (MB): 8192.00
        Memory slot #0 clockSpeed (GHz): 1.60
        Memory slot #0 type: DDR3
        Memory slot #1 capacity (MB): 8192.00
        Memory slot #1 clockSpeed (GHz): 1.60
        Memory slot #1 type: DDR3
        Memory slot #2 capacity (MB): 8192.00
        Memory slot #2 clockSpeed (GHz): 1.60
        Memory slot #2 type: DDR3
        Memory slot #3 capacity (MB): 8192.00
        Memory slot #3 clockSpeed (GHz): 1.60
        Memory slot #3 type: DDR3
        Virtual memory max (MB): 57262.66
        Virtual memory used (MB): 12961.04
        Swap memory total (MB): 24576.00
        Swap memory used (MB): 0.00
        JVM Flags: 1 total; -Xmx8G
        ModLauncher: 9.1.3+9.1.3+main.9b69c82a
        ModLauncher launch target: forgeserver
        ModLauncher naming: srg
        ModLauncher services:
                 mixin PLUGINSERVICE
                 eventbus PLUGINSERVICE
                 slf4jfixer PLUGINSERVICE
                 object_holder_definalize PLUGINSERVICE
                 runtime_enum_extender PLUGINSERVICE
                 capability_token_subclass PLUGINSERVICE
                 accesstransformer PLUGINSERVICE
                 runtimedistcleaner PLUGINSERVICE
                 mixin TRANSFORMATIONSERVICE
                 fml TRANSFORMATIONSERVICE
        FML Language Providers:
                minecraft@1.0
                lowcodefml@null
                javafml@null
        Mod List:
                server-1.18.2-20220404.173914-srg.jar             |Minecraft                     |minecraft                     |1.18.2              |SIDED_SETU|Manifest: NOSIGNATURE
                devices-merged-0.5.0.1.jar                        |Devices Mod Wrapper           |devices_forge                 |1                   |SIDED_SETU|Manifest: NOSIGNATURE
                forge-devices-0.5.0.1.jar                         |Devices Mod                   |devices                       |0.5.0.1             |ERROR     |Manifest: NOSIGNATURE
                forge-1.18.2-40.2.0-universal.jar                 |Forge                         |forge                         |40.2.0              |SIDED_SETU|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
                architectury-4.11.89-forge.jar                    |Architectury                  |architectury                  |4.11.89             |SIDED_SETU|Manifest: NOSIGNATURE
        Crash Report UUID: 59eeeeeb-be27-49b7-bf6e-d61a8b7ff79e
        FML: 40.2
        Forge: net.minecraftforge:40.2.0[14:16:26] [main/ERROR] [minecraft/Main]: Failed to start the minecraft server
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
        Devices Mod (devices) encountered an error during the common_setup event phase
§7java.lang.NoClassDefFoundError: net/minecraft/client/gui/GuiComponent
]
        at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:222) ~[fmlcore-1.18.2-40.2.0.jar%2343!/:?] {}
        at net.minecraftforge.fml.ModLoader.lambda$dispatchAndHandleError$21(ModLoader.java:187) ~[fmlcore-1.18.2-40.2.0.jar%2343!/:?] {}
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {}
        at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:187) ~[fmlcore-1.18.2-40.2.0.jar%2343!/:?] {}
        at net.minecraftforge.fml.ModLoader.lambda$loadMods$14(ModLoader.java:170) ~[fmlcore-1.18.2-40.2.0.jar%2343!/:?] {}
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {}
        at net.minecraftforge.fml.ModLoader.loadMods(ModLoader.java:170) ~[fmlcore-1.18.2-40.2.0.jar%2343!/:?] {}
        at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:33) ~[forge-1.18.2-40.2.0-universal.jar%2347!/:?] {re:classloading}
        at net.minecraft.server.Main.main(Main.java:112) ~[server-1.18.2-20220404.173914-srg.jar%2342!/:?] {re:classloading}
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
        at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:32) ~[fmlloader-1.18.2-40.2.0.jar%2317!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {}
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {}
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {}
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {}
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {}
        at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}
```

**Please complete the following information:**
 - OS: Windows 10
 - Minecraft version 1.18.2
 - Devices Mod 0.5.0.1
 - Architectury-4.11.89-forge

**FOR FORGE:**
 - Forge version 40.2.0

**Additional context**
It could be due to the mod doesn't have a Signature

**Additional mods used**
Only dependencies

**Comment by QboiDev** [comment]
Hmmm I think it's accessing client side code. 🤔

**Comment by 5stigma** [comment]
As extra, the crafting of motherboar with all its components doesn't work or I dont know how to craft it (in Minecraft 1.18.2)(I addid recipes with for the Laptops with CrafTweaker mod).

Thanks for attention.

**Comment by QboiDev** [comment]
It's indeed not possible to craft the motherboard *yet*. Since I couldn't figure out how to add the components seperately, seems like it needs some sort of NBT crafting, but can't find anything about it that works in newer versions without the use of another mod. But now I think of it, it may fit in the crafting table with every single component with it. So I might do that.

**Comment by 5stigma** [comment]
I used the following recipes, if it helps you:

1.- craftingTable.addShaped("laptops_devices_0", <item:devices:gray_laptop>, [[<item:devices:plastic_frame>, <item:devices:screen>, <item:devices:plastic_frame>], [<item:devices:wifi>, <item:devices:cpu>, <item:devices:hard_drive>], [<item:devices:ram>, <item:devices:motherboard>, <item:devices:gpu>]]);

2.- craftingTable.addShaped("laptops_devices_1", <item:devices:gray_laptop>, [[<item:devices:plastic_frame>, <item:devices:screen>, <item:devices:plastic_frame>], [<item:devices:wifi>, <item:devices:cpu>, <item:devices:solid_state_drive>], [<item:devices:ram>, <item:devices:motherboard>, <item:devices:gpu>]]);

**Comment by QboiDev** [comment]
I might be doing shapeless recipes, and adding a recipe for every colored laptop, and adding a dye with it.

**Comment by 5stigma** [comment]
I could do that for you, if you like. I will post it here, but only in CrafTweaker code (I have only used that).

**Comment by QboiDev** [comment]
I would need a `.json` recipe file actually. (The same as in datapacks)

**Comment by 5stigma** [comment]
[recipe_black_laptop.txt](https://github.com/Ultreon/devices-mod/files/11143514/recipe_black_laptop.txt)
Something like that? (.json is not supported to upload here)

**Comment by QboiDev** [comment]
> Something like that?

Yeah, but then shapeless, and using a dye.

**Comment by 5stigma** [comment]
I was thinking that the main crafting would be the black laptop, and from there add a recipe with the dyes using the laptop tag to be able to use any laptop + a dye to change the color, but this will probably reset the laptop usage. if you like i can do it this way.

Or I make a recipe for each color.

**Comment by QboiDev** [comment]
I just thought of something: why not add a custom block that allows adding component to the motherboard and such?

**Comment by 5stigma** [comment]
I tried it through tags and I couldn't :c ,I still don't know enough Java.

**Comment by QboiDev** [comment]
> I tried it through tags and I couldn't :c ,I still don't know enough Java.

It's not done through tags, it's done by using Java or another JVM Language code.

**Comment by QboiDev** [comment]
There seems to be a recipe already (the wool color relates to the color of laptop):
![image](https://user-images.githubusercontent.com/30625109/230799845-a6485332-d78e-4dad-af08-3e479dcab3c6.png)

Tbh the recipe is overkill.
Netherite ingots, ok. But 2 beacons? WUT.
This might be the work of Jab125. But at least it's craftable.
Also, there's no loottable, so breaking it would be fatal since there's no drops.

**Comment by 5stigma** [comment]
and, How the components would have any usage?

**Comment by 5stigma** [comment]
I am trying to make a code to be able to implement the component items to the MB, but, I don't know which is the code of the MB, to be able to implement the new code.

**Comment by QboiDev** [comment]
> and, How the components would have any usage?

I'm currently reworking the recipes.

**Comment by QboiDev** [comment]
I want to note here something, the 1.19.2 and 1.19.3 versions work. I can't seem to figure out one single client reference in the code. I guess we will need to wait for @Jab125

**Comment by Jab125** [comment]
> There seems to be a recipe already (the wool color relates to the color of laptop): ![image](https://user-images.githubusercontent.com/30625109/230799845-a6485332-d78e-4dad-af08-3e479dcab3c6.png)
> 
> Tbh the recipe is overkill. Netherite ingots, ok. But 2 beacons? WUT. This might be the work of Jab125. But at least it's craftable. Also, there's no loottable, so breaking it would be fatal since there's no drops.

placeholder recipe temporary

**Comment by Jab125** [comment]
i'll get the port to 1.18.2 done soon

**Comment by QboiDev** [comment]
> i'll get the port to 1.18.2 done soon

Finally!

**Comment by QboiDev** [comment]
Support for 1.18.2 has ended, unluckily this issue wasn't been able to be fixed before the EoL happened.
Currently 1.19.3 and 1.20.1 are supported versions.
